export const ASYNC_SUCCESS = 'ASYNC_SUCCESS';
export const ASYNC_ERROR = 'ASYNC_ERROR';
export const ASYNC_START = 'ASYNC_START';
export const ASYNC_END = 'ASYNC_END';

export const IS_AUTH = 'IS AUTH';
export const LOGIN_ERROR = 'LOGIN';

export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_SUCCESS = 'FETCH_USER';
export const FETCH_USER_ERROR = 'FETCH_USER';

export const FETCH_CHAT = 'FETCH_CHAT';
export const FETCH_CHAT_SUCCESS = 'FETCH_CHAT';
export const FETCH_CHAT_ERROR = 'FETCH_CHAT';

export const FETCH_EMPLOYEE = 'FETCH_EMPLOYEE';
export const FETCH_EMPLOYEE_SUCCESS = 'FETCH_EMPLOYEE';
export const FETCH_EMPLOYEE_ERROR = 'FETCH_EMPLOYEE';

export const FETCH_CONSULTANCE = 'FETCH_CONSULTANCE';
export const FETCH_CONSULTANCE_SUCCESS = 'FETCH_CONSULTANCE';
export const FETCH_CONSULTANCE_ERROR = 'FETCH_CONSULTANCE';

export const FETCH_MESSAGE = 'FETCH_MESSAGE';
export const FETCH_MESSAGE_SUCCESS = 'FETCH_MESSAGE';
export const FETCH_MESSAGE_ERROR = 'FETCH_MESSAGE';

export const UPDATE_FIELD_AUTH = 'UPDATE_FIELD_AUTH';

export const CREATE_CONSULTANCE = 'CREATE_CONSULTANCE';
export const CREATE_CONSULTANCE_SUCCESS = 'CREATE_CONSULTANCE_SUCCESS';
export const CREATE_CONSULTANCE_ERROR = 'CREATE_CONSULTANCE_ERROR';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const REGISTER = 'REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
